### ISSUE TITLE
Concatenate Strings

### ISSUE THREAD

**Issue by dangconnie** [rmotr-curriculum/free-python-course#19]
Can't seem to run test case on the "Concatenate Strings" assignment. The test case says "Test with empty string", but is that actually a different test for a different problem (like the Append X assignment)? Test case is not testing with empty string as label states.

**Comment by dakyion** [comment]
The same problem!
I can only run the code or submit it.

**Comment by sirpwn4g3** [comment]
I was able to finally pass this with no concatenation... text = "Hello World"

**Comment by santiagobasulto** [comment]
I just fixed the test. Concatenation should also work. The result is the same.
