### ISSUE TITLE
test case wont compile

### ISSUE THREAD

**Issue by pdujour** [rmotr-curriculum/free-python-course#25]
I am on the concatenate strings exercise and it will not compile when I input the following codes :

hello = "Hello"
world = "World"

# Final text should be:
# "Hello World"
text = "{} {}" .format(hello, world)

print(text)  # Use the Run Code button to try it on your own 

hello = "Hello"
world = "World"

# Final text should be:
# "Hello World"
text = hello + " " + world

print(text)  # Use the Run Code button to try it on your own

**Comment by sirpwn4g3** [comment]
I'm having the same issue, the "Run Test" just spins and never completes.

**Comment by santiagobasulto** [comment]
Thanks @pdujour and @sirpwn4g3. I've just fixed it.
